name = "Synthesis"
author = "shierru_r"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "18153a782f7ad9a515862d42d4bdc175f31cbe35ebc8dda5bccb7c9f7d5d6a64"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
