StartupEvents.rnsEnableDeposits(event => {
  event.overworld()
    .deposit('create_rns:deposit_coal', true)
    .deposit('create_rns:deposit_iron', true)
    .deposit('create_rns:deposit_copper', true)
    .deposit('create_rns:deposit_zinc', true)
    .deposit('create_rns:deposit_gold', true)
    .deposit('create_rns:deposit_lapis', true)
    .deposit('create_rns:deposit_redstone', true)
    .deposit('create_rns:deposit_tin', true)
    .deposit('create_rns:deposit_osmium', true)
    .deposit('create_rns:deposit_lead', true)
    .deposit('create_rns:deposit_nickel', true)
    .deposit('create_rns:deposit_silver', true)
    .deposit('create_rns:deposit_platinum', true)
    .deposit('create_rns:deposit_uranium', true)
    .deposit('create_rns:deposit_thorium', true)
    .spacing(48)
    .separation(12)

  event.nether()
    .deposit('create_rns:deposit_nether_gold', true)
    .deposit('create_rns:deposit_nether_quartz', true)
    .deposit('create_rns:deposit_nether_cobalt', true)
    .deposit('create_rns:deposit_nether_wolframite', true)
    .spacing(8)
    .separation(2)
})